Adicionando script de push image to gcp.

diff --git a/jenkins_scripts/push-image-to-gcp.jenkinsfile b/jenkins_scripts/push-image-to-gcp.jenkinsfile
--- a/jenkins_scripts/push-image-to-gcp.jenkinsfile
+++ b/jenkins_scripts/push-image-to-gcp.jenkinsfile
@@ -8,12 +8,34 @@ pipeline {
     REPOSITORY='mlopscase'
   }
   stages {
-    stage('Connect to GCP ') {
+    stage('Tag Image with. ') {
       steps {
+        script {
+          sh '''
+            export PROJECT_DIR=$(echo $GIT_PROJECT | awk -F/ '{print $NF}'| sed 's/.git//g')
+            export MODEL_VERSION=$(cat API/app/model_version.py | cut -d= -f2)
+            GIT_TAG=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1)
+            echo "$PROJECT_DIR:$MODEL_VERSION$GIT_TAG" > ${WORKSPACE}/image.txt
+          '''
+        }
+      }
+    }    
+    stage('Push image to Google Cloud Artifactory. ') {
+      when { 
+        environment name: 'PUSH_TO_ARTIFACTORY', value: 'yes' 
+      }
+      environment {
+        WORKSPACE_NAME='data-masters-workspace'
+        RESOURCE_GROUP='DataMasters'    
+        REGION='us-central1'
+        PROJECT_ID='mlopscase'
+        REPOSITORY='mlopscase'
+      }
+      steps {
+        echo 'Connect to GCP'
         script {
           withCredentials([file(credentialsId: 'GCLOUD_KEY_JSON', variable: 'GCLOUD_KEY_JSON')]) {
             sh '''
-              #####
               GCLOUD_LOGIN_INFO=mlops-service-account@mlopscase.iam.gserviceaccount.com
               GCLOUD_PROJECT=mlopscase
               gcloud auth activate-service-account $GCLOUD_LOGIN_INFO \
@@ -23,31 +45,27 @@ pipeline {
             '''
           }
         }
-      }
-    }
-    stage('Push image to Google Cloud Artifact Repository.') {
-      steps {
+        echo "Push image to Google Cloud Artifact Repository."
         script {
-          withCredentials([file(credentialsId: 'GCLOUD_KEY_JSON', variable: 'GCLOUD_KEY_JSON')]) {
-            sh '''
-              create_set_google_artifactory_repo () {
-                if ( ! gcloud artifacts repositories  list | grep "$REPOSITORY" )  ; then  
-                  echo "Repositório não existe. Abortando."
-                  exit 1
-                fi
-                echo "Configurando repositório para push"
-                sudo gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
-              }
-              create_set_google_artifactory_repo
+          sh '''
+            create_set_google_artifactory_repo () {
+              if ( ! gcloud artifacts repositories  list | grep "$REPOSITORY" )  ; then  
+                echo "Repositório não existe. Abortando."
+                exit 1
+              fi
+              echo "Configurando repositório para push"
+              sudo gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
+            }
+            create_set_google_artifactory_repo
 
-              #Clone MLOPS project
-              CONTAINER_IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE"
-              echo "tageando imagem."
-              sudo docker tag $IMAGE $CONTAINER_IMAGE
-              echo "Build step: Publicando a imagem no Google Artifact Registry."  
-              sudo docker push $CONTAINER_IMAGE
-            '''
-          }
+            #Clone MLOPS project
+            IMAGE=`cat  ${WORKSPACE}/image.txt`
+            CONTAINER_IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE"
+            echo "tageando imagem."
+            sudo docker tag $IMAGE $CONTAINER_IMAGE
+            echo "Build step: Publicando a imagem no Google Artifact Registry."  
+            sudo docker push $CONTAINER_IMAGE
+          '''
         }
       }
     }
